const fs = require('fs');
const path = require('path');

const wasmPath = path.join(__dirname, '../wasm/pkg/bionic_wasm_bg.wasm');
const outputPath = path.join(__dirname, '../src/wasm_bytes.ts');

try {
  if (!fs.existsSync(wasmPath)) {
    console.error(`Error: WASM file not found at ${wasmPath}. Make sure wasm-pack build ran successfully.`);
    process.exit(1);
  }

  const wasmBuffer = fs.readFileSync(wasmPath);
  const wasmBase64 = wasmBuffer.toString('base64');

  const fileContent = `// This file is auto-generated by scripts/inline-wasm.js. Do not edit manually.
export const WASM_BASE64 = "${wasmBase64}";
`;

  fs.writeFileSync(outputPath, fileContent, 'utf-8');
  console.log(`Successfully inlined WASM to ${outputPath} (${(wasmBuffer.length / 1024).toFixed(2)} KB)`);
} catch (error) {
  console.error('Failed to inline WASM:', error);
  process.exit(1);
}
